# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
platform_packages:
  - bzip2-devel
  - gcc
  - glibc-common
  - libffi-devel
  - openldap
  - openldap-clients
  - openssl-devel
  - zlib-devel

platform_nodejs_package: "@nodejs:16"

platform_python_version: 3.9
platform_python_executable: "/usr/bin/python{{ platform_python_version }}"
platform_pip_executable: "/usr/bin/pip{{ platform_python_version }}"

platform_python_packages:
  - python39
  - python39-pip

platform_base_python_dependencies:
  - pip
  - setuptools
  - wheel

platform_app_python_dependencies:
  - textfsm==1.1.2
  - jinja2==2.11.3
  - markupsafe==2.0.1
  - pymongo

platform_mongodb_version: 5.0

platform_mongodb_tools_packages:
  - mongodb-database-tools
  - mongodb-mongosh

platform_mongo_shell: mongosh
