# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

platform_packages:
  - glibc-common
  - openldap
  - openldap-clients
  - openssl

iap_nodejs_package: "@nodejs:20"

python_version: 3.11
python_executable: "/usr/bin/python{{ python_version }}"
pip_executable: "/usr/bin/pip{{ python_version }}"

python_packages:
  - python3.11
  - python3.11-pip

base_python_dependencies:
  - pip
  - setuptools
  - wheel

app_python_dependencies:
  - jinja2==3.1.2
  - markupsafe==2.1.4
  - pymongo
  - textfsm==1.1.3

mongodb_release_url: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/7.0/x86_64/
mongodb_gpgkey_url: https://www.mongodb.org/static/pgp/server-7.0.asc

mongodb_tools_packages:
  - mongodb-database-tools
  - mongodb-mongosh

mongo_shell: mongosh
