# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
platform_nodejs_package_default:
  "8": "@nodejs:20/common"
  "9": "@nodejs:20"
  "2023": "nodejs20"

platform_python_version_default:
  "8": 3.11
  "9": 3.11
  "2023": 3.11

platform_python_packages_default:
  "8":
    - python3.11
    - python3.11-pip
  "9":
    - python3.11
    - python3.11-pip
  "2023":
    - python3.11
    - python3.11-pip

platform_python_app_dependencies_default:
  "8":
    - jinja2==3.1.2
    - markupsafe==2.1.4
    - textfsm==1.1.3
  "9":
    - jinja2==3.1.2
    - markupsafe==2.1.4
    - textfsm==1.1.3
  "2023":
    - jinja2==3.1.2
    - markupsafe==2.1.4
    - textfsm==1.1.3

platform_hw_specs:
  "dev":
    "cpu_count": 8
    "ram_size": 32
    "disk_size": 250
  "test":
    "cpu_count": 16
    "ram_size": 64
    "disk_size": 250
  "production":
    "cpu_count": 16
    "ram_size": 64
    "disk_size": 250
