# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# Location of mongo conf file
mongodb_conf_file: /etc/mongod.conf

# Directory that stores mongodb data files
mongodb_data_dir: /var/lib/mongo

# Target path for writing mongodb log files
mongodb_log_dir: /var/log/mongodb

# Directory that stores the mongodb pid file
mongodb_pid_dir: /var/run/mongodb

# The base directory for SSL certs and key files
mongodb_ssl_root_dir: /etc/ssl/certs

# Key file destination location
# The key file is used to authenticate members of a replica set
mongodb_auth_keyfile_destination: "{{ mongodb_ssl_root_dir }}/mongodb/mongo-replicaset-key.pem"

# Destination location of the certificate key file used for TLS connections
mongodb_cert_keyfile_destination: "{{ mongodb_ssl_root_dir }}/mongodb/mongo-certificate.pem"

# Destination location of the CA root file used for TLS connections
mongodb_root_ca_file_destination: "{{ mongodb_ssl_root_dir }}/mongodb/mongo-rootCA.pem"

# The Mongo user and group
mongodb_owner: mongod
mongodb_group: mongod

# The default admin database name
mongodb_admin_db_name: admin

# Flag to enable/disable IPv6
mongodb_bind_ipv6: true

# The hostnames and/or IP addresses and/or full Unix domain socket paths on
# which mongos or mongod should listen for client connections. You may attach
# mongos or mongod to any interface. To bind to multiple addresses, enter a
# list of comma-separated values.
#
# The inventory_hostname will be automatically added to mongodb_bind_addrs.
#
# If mongodb_bind_ipv6 is set to true, '::1' will be added to mongodb_bind_addrs.
mongodb_bind_addrs: 127.0.0.1

# The TCP port on which the MongoDB instance listens for client connections.
mongodb_port: "{{ mongodb_port_default }}"

# Default Itential database name in MongoDB
mongodb_itential_db_name: itential

# Feature flags that can be overridden in the hosts file
# Essentially, a default installation will not have replication, authorization,
# or TLS settings applied.
mongodb_replication_enabled: false
mongodb_auth_enabled: true
mongodb_tls_enabled: false

# Default mongo user names
mongodb_user_admin: admin
mongodb_user_itential: itential

# Default mongo user passwords
# These are meant to be changed by the customer. By default they are meant to
# be predictable and simple.
mongodb_user_admin_password: admin
mongodb_user_itential_password: itential

# The name of the mongo replica set
mongodb_replset_name: "{{ mongodb_replset_name_default }}"

# Default location for the certification report files
mongodb_certify_report_dir: /tmp/itential-reports/mongodb
