# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# Pluggable Authentication Module (PAM) limits
mongodb_pam_limit_nproc: 32000
mongodb_pam_limit_nofile: 64000
