# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Download Python rpms
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-rpms
  vars:
    offline_download_method: yum_module
    offline_download_packages: "{{ python_packages }}"
    offline_download_dir: "{{ rpms_download_dir_target_node }}"

- name: Copy rpms to control node
  ansible.builtin.import_role:
    name: offline
    tasks_from: fetch-packages
  vars:
    offline_src_dir: "{{ rpms_download_dir_target_node }}"
    offline_dest_dir: "{{ rpms_download_dir_control_node }}"

- name: Install Python
  ansible.builtin.include_role:
    name: python
  tags: install_python
  vars:
    python_packages: "{{ mongodb_python_packages }}"

- name: Download base Python dependencies
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-wheels
  vars:
    offline_wheel_files: "{{ base_python_dependencies }}"
    offline_download_dir: "{{ wheels_download_dir_target_node }}/base"
  when:
    - base_python_dependencies is defined
    - base_python_dependencies | length > 0

- name: Download MongoDB Python dependencies
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-wheels
  vars:
    offline_with_deps: true
    offline_wheel_files: "{{ app_python_dependencies }}"
    offline_download_dir: "{{ wheels_download_dir_target_node }}/app"
  when:
    - app_python_dependencies is defined
    - app_python_dependencies | length > 0

- name: Uninstall Python rpms
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
    autoremove: true
  with_items: "{{ python_install_result.results | selectattr('changed', 'equalto', true) | map(attribute='item') }}"
