# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Allow yum to update MongoDB packages
  ansible.builtin.lineinfile:
    path: /etc/yum.conf
    line: exclude=mongodb-org*
    state: absent

- name: Install MongoDB rpms (offline)
  ansible.builtin.import_role:
    name: offline
    tasks_from: install-rpms
