# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# Key file destination location
# The key file is used to authenticate members of a replica set
mongo_auth_keyfile_destination: /etc/ssl/mongo-replicaset-key.pem
