# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This task will install a remi RPM as the repo
- name: Install remi RPM
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ redis_repo_url[ansible_distribution_major_version] }}"
    state: present
    disable_gpg_check: true

# This task installs the redis RPM thus
# enabling control of the redis version to the release files where there is a
# mapping of "versions" to RPM locations.
- name: Install Redis RPM
  ansible.builtin.dnf:
    name: '{{ redis_packages[ansible_distribution_major_version] }}'
    state: present
    update_cache: true
