# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

epel_location: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

os_packages:
  - coreutils
  - gcc-c++
  - make
  - ntp
  - openssl

security_packages:
  - audit
  - checkpolicy
  - iptables
  - libselinux
  - libselinux-utils
  - policycoreutils
  - policycoreutils-python
  - selinux-policy
  - selinux-policy-mls
  - selinux-policy-targeted
  - setools-console

operational_packages:
  - bind-utils
  - curl
  - dos2unix
  - git
  - gzip
  - jq
  - man
  - sysstat
  - tcpdump
  - telnet
  - unzip
  - wget
  - zip
