# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

os_packages:
  - chrony
  - coreutils
  - openssl
  - yum-utils
  - dnf-plugins-core
  - python3-dnf-plugins-core

security_packages:
  - audit
  - checkpolicy
  - iptables
  - libselinux
  - libselinux-utils
  - policycoreutils
  - policycoreutils-python-utils
  - selinux-policy
  - selinux-policy-mls
  - selinux-policy-targeted
  - setools-console

operational_packages:
  - bind-utils
  - curl
  - dos2unix
  - git
  - gzip
  - jq
  - man
  - rsyslog
  - sudo
  - sysstat
  - tar
  - tcpdump
  - telnet
  - unzip
  - wget
  - which
  - zip
