# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
gateway_packages:
  - gcc-c++
  - make
  - selinux-policy
  - selinux-policy-targeted

gateway_build_packages:
  - gcc-c++
  - make
  - python3-devel

gateway_python_version: 3.9
gateway_python_executable: "/usr/bin/python{{ python_version }}"
gateway_pip_executable: "/usr/bin/pip{{ python_version }}"

gateway_python_packages:
  - python3
  - python3-pip
  - python3-devel

gateway_python_base_dependencies:
  - pip==24.0
  - setuptools==69.0.3
  - wheel==0.42.0

gateway_python_app_dependencies:
  - ansible-pylibssh==1.1.0
  - flask-ldap3-login==0.9.18
  - grpcio==1.53.0
  - hvac==1.0.2
  - ldap3==2.9.1
  - ncclient==0.6.10
  - netmiko==4.1.2
  - nornir==3.3.0
  - nornir-netmiko==0.2.0
  - nornir-utils==0.2.0
  - pygnmi==0.8.9

iag_ansible_version: ansible==8.7.0
