# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
gateway_packages:
  - selinux-policy
  - selinux-policy-targeted

gateway_build_packages_map:
  "8":
    - gcc-c++
    - libssh-devel
    - make
    - pkgconf-pkg-config
    - python39-devel
  "9":
    - gcc-c++
    - libssh-devel
    - make
    - pkgconf-pkg-config
    - python3-devel
  "2023":
    - gcc-c++
    - libssh-devel
    - make
    - pkgconf-pkg-config
    - python3-devel

# Backwards compatible variable name references the appropriate list from the map
gateway_build_packages: "{{ gateway_build_packages_map[ansible_distribution_major_version] }}"

gateway_python_version: 3.9
gateway_python_executable: "/usr/bin/python{{ gateway_python_version }}"
gateway_pip_executable: "/usr/bin/pip{{ gateway_python_version }}"

gateway_python_packages_map:
  "8":
    - python39
    - python39-pip
  "9":
    - python3
    - python3-pip
  "2023":
    - python3
    - python3-pip

# Backwards compatible variable name references the appropriate list from the map
gateway_python_packages: "{{ gateway_python_packages_map[ansible_distribution_major_version] }}"

gateway_python_base_dependencies:
  - pip==24.0
  - setuptools==69.0.3
  - wheel==0.42.0

# Python modules that require a build. For offline installs, these will be built using 'pip wheel'.
gateway_python_wheel_build_dependencies:
  - ansible-pylibssh==1.3.0
  - mypy_extensions==0.4.4
  - ncclient==0.6.10
  - netifaces==0.10.9
  - pygnmi==0.8.9

# These Python modules are pinned here because we are using 'pip download' and not 'pip install'
# for offline installs.
gateway_python_app_dependencies:
