# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Put the HTTPS key file in the correct location
  ansible.builtin.copy:
    remote_src: true
    src: "{{ iap_install_dir }}/current/keys/key.pem"
    dest: "{{ iap_install_dir }}/keys/itential.key"
    mode: 0400
    owner: "{{ iap_user }}"
    group: "{{ iap_group }}"

- name: Put the HTTPS cert file in the correct location
  ansible.builtin.copy:
    remote_src: true
    src: "{{ iap_install_dir }}/current/keys/cert.pem"
    dest: "{{ iap_install_dir }}/keys/itential.cert"
    mode: 0400
    owner: "{{ iap_user }}"
    group: "{{ iap_group }}"

- name: Copy MongoDB root CA file to the appropriate location
  ansible.builtin.copy:
    src: "{{ mongo_root_ca_file_source }}"
    dest: "{{ itential_root_ca_file_destination }}"
    mode: 0400
    group: "{{ iap_group }}"
    owner: "{{ iap_user }}"
  when:
    - mongodb_tls | bool
