# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Install jinja2
  ansible.builtin.pip:
    name: jinja2
    version: "{{ iap_jinja2_version[ ansible_distribution_major_version ] }}"
    executable: /usr/local/bin/pip3

- name: Update release file with jinja2 version
  ansible.builtin.lineinfile:
    path: "{{ itential_release_file }}"
    line: "JINJA2={{ iap_jinja2_version[ ansible_distribution_major_version ] }}"
    create: true

# Immediately downgrade the markupsafe package that is installed
# with jinja2 because it has its own dependency problems and this
# version is the safest that we have successfully tested against.
- name: Downgrade Markupsafe package
  ansible.builtin.pip:
    name: markupsafe
    version: "{{ iap_markupsafe_version }}"
    executable: /usr/local/bin/pip3

- name: Update release file with markupsafe version
  ansible.builtin.lineinfile:
    path: "{{ itential_release_file }}"
    line: "MARKUPSAFE={{ iap_markupsafe_version }}"
    create: true
