# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)---

- name: Install python3 with yum
  ansible.builtin.yum:
    name: python3

- name: Add python3 symlink
  ansible.builtin.file:
    state: link
    src: /usr/bin/python3.9
    path: /usr/local/bin/python3

- name: Capture python version
  ansible.builtin.command:
    cmd: /usr/local/bin/python3 -V
  register: python_installed_version

- name: Update release file
  ansible.builtin.lineinfile:
    path: "{{ itential_release_file }}"
    line: "PYTHON={{ python_installed_version.stdout }}"
    create: true

- name: Install pip3
  ansible.builtin.command:
    cmd: python -m ensurepip --upgrade

- name: Capture pip3 version
  ansible.builtin.command:
    cmd: /usr/local/bin/pip3 -V
  register: pip_installed_version

- name: Update release file
  ansible.builtin.lineinfile:
    path: "{{ itential_release_file }}"
    line: "PIP={{ pip_installed_version.stdout }}"
    create: true
