# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Create rabbitmq environment file
  ansible.builtin.template:
    owner: "{{ rabbitmq_owner }}"
    group: "{{ rabbitmq_group }}"
    mode: "0600"
    dest: "{{ rabbitmq_env_config }}"
    src: rabbitmq-env.conf.j2
  when: >
    rabbitmq_home_dir != rabbitmq_default_home_dir or
    rabbitmq_port != rabbitmq_default_port or
    (rabbitmq_distribution_buffer_size is defined and rabbitmq_distribution_buffer_size != rabbitmq_default_distribution_buffer_size)

- name: Handle custom rabbitmq directory
  when: rabbitmq_home_dir != rabbitmq_default_home_dir
  block:
    - name: Create rabbitmq runtime directory
      ansible.builtin.file:
        path: "{{ rabbitmq_home_dir }}"
        state: directory
        owner: "{{ rabbitmq_owner }}"
        group: "{{ rabbitmq_group }}"
        mode: "0755"

    - name: Remove default rabbitmq runtime directory
      ansible.builtin.file:
        path: "{{ rabbitmq_default_home_dir }}"
        state: absent

    - name: Set rabbitmq user home directory
      ansible.builtin.user:
        name: rabbitmq
        home: "{{ rabbitmq_home_dir }}"

    - name: Update service script with rabbitmq runtime directory
      ansible.builtin.lineinfile:
        path: /usr/lib/systemd/system/rabbitmq-server.service
        line: "WorkingDirectory={{ rabbitmq_home_dir }}"
        search_string: "WorkingDirectory="

- name: Create rabbitmq log directory
  ansible.builtin.file:
    path: "{{ rabbitmq_log_dir }}"
    state: directory
    owner: "{{ rabbitmq_owner }}"
    group: "{{ rabbitmq_group }}"
    mode: "0755"
  when: rabbitmq_log_dir != rabbitmq_default_log_dir
