# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Validate distribution major version
  ansible.builtin.fail:
    msg: Download not supported for version 7
  when: ansible_distribution_major_version == "7"

- name: Validate offline_install variable
  ansible.builtin.fail:
    msg: offline_install must be set to false for download
  when:
    - offline_install is defined
    - offline_install

- name: Include release vars
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "release-{{ iap_release }}.yaml"
    - "release-undefined.yaml"

- name: Check for valid RabbitMQ release
  ansible.builtin.fail:
    msg: "missing or invalid rabbitmq_packages"
  when: rabbitmq_packages == "UNDEFINED"

- name: Import PackageCloud signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://packagecloud.io/rabbitmq/erlang/gpgkey
  when: ansible_distribution_major_version | int <= 8   # SHA-1 is deprecated in RHEL 9

- name: Import RabbitMQ primary signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc

- name: Import RabbitMQ signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
  when: ansible_distribution_major_version | int <= 8   # SHA-1 is deprecated in RHEL 9

# Install yum repos for the appropriate erlang and rabbitmq version
- name: Install Erlang repo
  ansible.builtin.yum_repository:
    name: rabbitmq_erlang
    description: rabbitmq_erlang
    owner: root
    group: root
    mode: "0644"
    baseurl: "{{ rabbitmq_erlang_repo_baseurl }}"
    gpgcheck: true
    gpgkey: https://packagecloud.io/rabbitmq/erlang/gpgkey
    enabled: true
    repo_gpgcheck: false
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Install RabbitMQ repo
  ansible.builtin.yum_repository:
    name: rabbitmq_server
    description: rabbitmq_server
    owner: root
    group: root
    mode: "0644"
    baseurl: "{{ rabbitmq_server_repo_baseurl }}"
    gpgcheck: true
    gpgkey: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    enabled: true
    repo_gpgcheck: false
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300

- name: Download Rabbitmq rpms
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-rpms
  vars:
    download_method: yum_module
    download_packages: "{{ rabbitmq_packages[ansible_distribution_major_version] }}"
    download_dir: "{{ rabbitmq_rpms_download_dir_target_node }}"

- name: Copy rpms to control node
  ansible.builtin.import_role:
    name: offline
    tasks_from: fetch-packages
  vars:
    src_dir: "{{ rabbitmq_rpms_download_dir_target_node }}"
    dest_dir: "{{ rabbitmq_rpms_download_dir_control_node }}"
