# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Import PackageCloud signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://packagecloud.io/rabbitmq/erlang/gpgkey
  when: ansible_distribution_major_version | int <= 8   # SHA-1 is deprecated in RHEL 9

- name: Import rabbitmq primary signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc

- name: Import rabbitmq signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
  when: ansible_distribution_major_version | int <= 8   # SHA-1 is deprecated in RHEL 9

- name: Install erlang repo
  ansible.builtin.yum_repository:
    name: rabbitmq_erlang
    description: rabbitmq_erlang
    owner: "root"
    group: "root"
    mode: 0644
    baseurl: "{{ rabbitmq_erlang_repo_baseurl }}"
    gpgcheck: true
    gpgkey:
      - https://packagecloud.io/rabbitmq/erlang/gpgkey
    enabled: true
    repo_gpgcheck: false
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
  when: install_yum_repos | bool

- name: Install rabbitmq repo
  ansible.builtin.yum_repository:
    name: rabbitmq_server
    description: rabbitmq_server
    owner: "root"
    group: "root"
    mode: 0644
    baseurl: "{{ rabbitmq_server_repo_baseurl }}"
    gpgcheck: true
    gpgkey:
      - https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    enabled: true
    repo_gpgcheck: false
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
  when: install_yum_repos | bool

# Installs the packages enabled by the above repos
- name: Install packages
  ansible.builtin.yum:
    name: "{{ rabbitmq_packages[ ansible_distribution_major_version ] }}"
    update_cache: true
