# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# The default user that runs vault
vault_user: vault

# The default group that runs vault
vault_group: vault

# The default port of the vault server
vault_port: 8200
