# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# A toggle to instruct the webserver to include HTTP cache control headers on the response.
platform_webserver_cache_control_enabled: false

# Timeout to use for incoming HTTP requests to the platform API, in milliseconds.
platform_webserver_timeout: 300000

# The value of the HTTP Access-Control-Allow-Origin header returned to clients.
platform_webserver_response_header_access_control_allow_origin: "*"

# If true, allows the webserver to respond to insecure HTTP requests.
platform_webserver_http_enabled: true

# The port on which the webserver listens for HTTP requests.
platform_webserver_http_port: 3000

# If true, allows the webserver to respond to secure HTTPS requests.
platform_webserver_https_enabled: false

# The port on which the webserver listens for HTTPS requests.
platform_webserver_https_port: 3443

# The path to the public key file used for HTTPS connections.
platform_webserver_https_key: "server.key"

# The passphrase for the private key used to enable TLS sessions.
platform_webserver_https_passphrase:

# The path to the certificate file used for HTTPS connections.
platform_webserver_https_cert: "server.crt"

# The set of allowed SSL/TLS protocol versions.
platform_webserver_https_secure_protocol: TLSv1_2_method

# The allowed SSL/TLS cipher suite.
platform_webserver_https_ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA" # noqa line-length yaml[line-length]

# Specifies the number of renegotiations that are allowed in a single HTTPS connection.
platform_webserver_https_client_reneg_limit: 3

# Specifies the time renegotiation window in seconds for a single HTTPS connection.
platform_webserver_https_client_reneg_window: 600

# The set of allowed HTTP verbs in addition to those defined in the standard HTTP/1.1 protocol.
platform_webserver_http_allowed_optional_verbs:
