# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Install OS Packages
  ansible.builtin.yum:
    name: "{{ os_packages }}"
    state: present
    validate_certs: false
    skip_broken: true
    update_cache: true

- name: Install Security Packages
  ansible.builtin.yum:
    name: "{{ security_packages }}"
    state: present

- name: Install Operations Packages
  ansible.builtin.yum:
    name: "{{ operational_packages }}"
    state: present
