# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# The keys represent the EL major version (ansible_distribution_major_version)

# The redis_packages_default is used when the redis_install_from_source is set to 'false'
redis_packages_default:
  "8":
    - "@redis:remi-7.2"
  "9":
    - "@redis:remi-7.2"
  "2023":
    - "@redis:remi-7.2"

# The redis_source_url_default is used when the redis_install_from_source is set to 'true'
redis_source_url_default:
  "8": "https://github.com/redis/redis/archive/7.4.6.tar.gz"
  "9": "https://github.com/redis/redis/archive/7.4.6.tar.gz"
  "2023": "https://github.com/redis/redis/archive/7.4.6.tar.gz"
