# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# The keys here are intended to represent the Redhat/Rocky/Centos major version

# The redis_packages and redis_remi_repo_url are used when the
# redis_install_method is set to 'remi_repo'
redis_packages_default:
  "7":
    - redis-6.2*
  "8":
    - "@redis:remi-6.2"

# The redis_source_url and redis_build_packages are used when the
# redis_install_method is set to 'source'
redis_source_url_default:
  "7": "https://github.com/redis/redis/archive/6.2.14.tar.gz"
  "8": "https://github.com/redis/redis/archive/6.2.14.tar.gz"
