# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

# The file containing the installed components and versions
itential_release_file: /etc/iap-release

# Flag to toggle the installation of yum repositories.
# If set to true (default), repositories will be installed in /etc/yum.repos.d.
# If set to false, repositories will not be installed and customers will be
# required to configure them.  This will allow customers to use internal
# repositories.
install_yum_repos: true

# Offline install variables
offline_install: false

# Note that the packages_path is set in the defaults for each role
itential_packages_path: "itential_packages/{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}"
rpms_path: "{{ packages_path }}/rpms"
wheels_path: "{{ packages_path }}/wheels"
archives_path: "{{ packages_path }}/archives"
adapters_path: "{{ packages_path }}/adapters"
ansible_collections_path: "{{ packages_path }}/ansible_collections"

packages_download_root_control_node: "{{ playbook_dir }}/files"
packages_download_dir_control_node: "{{ packages_download_root_control_node }}/{{ packages_path }}"
rpms_download_dir_control_node: "{{ packages_download_dir_control_node }}/rpms"
wheels_download_dir_control_node: "{{ packages_download_dir_control_node }}/wheels"
archives_download_dir_control_node: "{{ packages_download_dir_control_node }}/archives"
adapters_download_dir_control_node: "{{ packages_download_dir_control_node }}/adapters"
ansible_collections_download_dir_control_node: "{{ packages_download_dir_control_node }}/ansible_collections"

packages_download_root_target_node: /var/tmp
packages_download_dir_target_node: "{{ packages_download_root_target_node }}/{{ packages_path }}"
rpms_download_dir_target_node: "{{ packages_download_dir_target_node }}/rpms"
wheels_download_dir_target_node: "{{ packages_download_dir_target_node }}/wheels"
archives_download_dir_target_node: "{{ packages_download_dir_target_node }}/archives"
adapters_download_dir_target_node: "{{ packages_download_dir_target_node }}/adapters"
ansible_collections_download_dir_target_node: "{{ packages_download_dir_target_node }}/ansible_collections"
