# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
preflight_directory: "/tmp/preflight"

# default mount to check
preflight_mounts: "/"

# default env specs to check
preflight_env: dev

# defaults for running and ignoring the preflight checks
preflight_run_checks: false
ignore_preflight_checks: true
