# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# The directory where certs and other stuff are stored.
rabbitmq_ssl_dir: /etc/rabbitmq/ssl

rabbitmq_ssl_port: 5671
