# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Check the auth status
  when: inventory_hostname in groups.mongodb
  block:
    - name: Default auth enabled flag
      ansible.builtin.set_fact:
        mongodb_auth_enabled: false

    - name: Check if auth is enabled
      community.mongodb.mongodb_shell:
        login_user: "{{ mongo_auth_enabled is defined and mongo_auth_enabled | ternary('admin', omit) }}"
        login_password: "{{ mongo_auth_enabled is defined and mongo_auth_enabled | ternary(mongo_user_admin_password, omit) }}"
        login_port: "{{ mongo_port }}"
        mongo_cmd: auto
        db: admin
        eval: "db.getUsers()"
      register: get_users_result
      changed_when: false
      failed_when: false

    - name: Set auth enabled flag
      ansible.builtin.set_fact:
        mongodb_auth_enabled: true
      when:
        - '"requires authentication" in get_users_result.msg or "not authorized" in get_users_result.msg'
