# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

rabbitmq_packages:
  "7":
    - socat
    - logrotate
    - erlang-23.3.4.11
    - rabbitmq-server-3.10.0
  "8":
    - socat
    - logrotate
    - erlang-25.3.2.2
    - rabbitmq-server-3.11.7
  "9":
    - socat
    - logrotate
    - erlang-25.3.2.2
    - rabbitmq-server-3.12.0