# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

# TODO: Can this file be removed?

- name: Create the mongodb backup directory
  ansible.builtin.file:
    path: "{{ platform_install_dir }}/current/backups"
    state: directory
    mode: "0775"
    owner: "{{ platform_user }}"
    group: "{{ platform_group }}"

- name: Build mongo connection string from template, set as fact
  ansible.builtin.set_fact:
    mongo_connection_string: "{{ lookup('ansible.builtin.template', 'mongo-connection-string.j2', lstrip_blocks=true) | trim }}"

- name: Backup mongodb itential database
  ansible.builtin.command:
    argv:
      - mongodump
      - --out="{{ platform_install_dir }}/current/backups"
      - --gzip
      - "{{ mongo_connection_string }}"
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc > 0
