# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# Check if firewalld is running, if it is then open the appropriate ports
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Open HTTP Port on FirewallD Public Zone
  ansible.posix.firewalld:
    port: "{{ platform_http_port }}/tcp"
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when:
    - ansible_facts.services["firewalld.service"] is defined
    - ansible_facts.services["firewalld.service"].state == "running"
    - ansible_facts.services["firewalld.service"].status == "enabled"
    - not platform_https | bool

- name: Open HTTPS Port on FirewallD Public Zone
  ansible.posix.firewalld:
    port: "{{ platform_https_port }}/tcp"
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when:
    - ansible_facts.services["firewalld.service"] is defined
    - ansible_facts.services["firewalld.service"].state == "running"
    - ansible_facts.services["firewalld.service"].status == "enabled"
    - platform_https | bool
