# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Check whether SELinux is enabled
  ansible.builtin.command: /usr/sbin/selinuxenabled
  changed_when: false
  register: selinux_status
  failed_when: selinux_status.rc > 1

- name: Configure SELinux when using custom install directory
  when:
    - selinux_status.rc == 0
    - platform_install_dir != "/opt/itential"
  block:
    - name: Set SELinux to allow systemd to use custom install directory
      community.general.sefcontext:
        target: "{{ platform_install_dir }}/current"
        setype: bin_t

    - name: Reload SELinux policy
      ansible.builtin.command: restorecon -irv "{{ platform_install_dir }}/current"
      register: restorecon_result
      changed_when: restorecon_result.rc == 0
      failed_when:
        - restorecon_result.rc is defined
        - restorecon_result.rc > 0
