# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Download IAP rpms
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-rpms
  vars:
    download_method: yum_module
    download_packages: "{{ platform_packages }}"
    download_dir: "{{ rpms_download_dir_target_node }}"
