# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Download Python RPMs
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-rpms
  vars:
    offline_download_method: yum_module
    offline_download_packages: "{{ platform_python_packages }}"
    offline_download_dir: "{{ offline_rpms_download_dir_target_node }}"

- name: Copy RPMs to control node
  ansible.builtin.import_role:
    name: offline
    tasks_from: fetch-packages
  vars:
    offline_src_dir: "{{ offline_rpms_download_dir_target_node }}"
    offline_dest_dir: "{{ offline_rpms_download_dir_control_node }}"

- name: Install Python
  ansible.builtin.include_tasks:
    file: install-python.yml
  tags: install_python

- name: Download base Python dependencies
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-wheels
  vars:
    offline_wheel_files: "{{ platform_python_base_dependencies }}"
    offline_download_dir: "{{ offline_wheels_download_dir_target_node }}/base"
    offline_pip_executable: "{{ platform_pip_executable }}"
  when:
    - platform_python_base_dependencies is defined
    - platform_python_base_dependencies | length > 0

- name: Download Itential Platform Python dependencies
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-wheels
  vars:
    offline_with_deps: true
    offline_wheel_files: "{{ platform_python_app_dependencies }}"
    offline_download_dir: "{{ offline_wheels_download_dir_target_node }}/app"
    offline_pip_executable: "{{ platform_pip_executable }}"
  when:
    - platform_python_app_dependencies is defined
    - platform_python_app_dependencies | length > 0

- name: Uninstall Python RPMs
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
    autoremove: true
  with_items: "{{ python_install_result.results | selectattr('changed', 'equalto', true)
                    | map(attribute='item') }}"
