# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

- name: Install NodeJS repo
  ansible.builtin.import_tasks:
    file: install-nodejs-repo.yml
  when: platform_nodejs_repo_url is defined

- name: Install NodeJS
  ansible.builtin.dnf:
    name: "{{ platform_nodejs_package }}"
    state: present
  register: nodejs_install_result
  when: not offline_install_enabled

- name: Install NodeJS (offline)
  ansible.builtin.include_role:
    name: offline
    tasks_from: install-rpms
  vars:
    offline_rpms_path: "{{ platform_offline_control_node_rpms_dir }}/nodejs"
  when: offline_install_enabled
