# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Install nodejs if RHEL 8 or 9
  when: not offline_install_enabled
  block:
    # Enable and install the module if the profile is defined
    # https://dnf.readthedocs.io/en/latest/command_ref.html#module-switch-to-command-label
    - name: DNF switch to the nodejs module (if profile is defined)
      ansible.builtin.command: dnf module switch-to -y "{{ platform_nodejs_package }}"
      register: result
      changed_when: '"Enabling module streams" in result.stdout'
      when: "'/' in platform_nodejs_package"

    # Install the module if the profile is not defined
    - name: DNF install nodejs
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      register: nodejs_install_result
      with_items: "{{ platform_nodejs_package }}"
      when: "'/' not in platform_nodejs_package"
