# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Install NodeJS on RedHat (online)
  when:
    - ansible_distribution == "RedHat"
    - not offline_install_enabled
  block:
    # Enable and install the module if the profile is defined
    # https://dnf.readthedocs.io/en/latest/command_ref.html#module-switch-to-command-label
    - name: DNF switch to the nodejs module (if profile is defined)
      ansible.builtin.command: dnf module switch-to -y "{{ platform_nodejs_package }}"
      register: result
      changed_when: '"Enabling module streams" in result.stdout'
      when: "'/' in platform_nodejs_package"

    # Install the module if the profile is not defined
    - name: DNF install NodeJS
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      register: nodejs_install_result
      with_items: "{{ platform_nodejs_package }}"
      when: "'/' not in platform_nodejs_package"

- name: Install NodeJS AL23 on Amazon Linux
  when:
    - ansible_distribution == "Amazon"
    - not offline_install_enabled
  block:
    - name: Create temp working dir
      ansible.builtin.tempfile:
        state: directory
      register: workingdir

    - name: Download NodeJS repo install script
      ansible.builtin.get_url:
        url: "{{ platform_nodejs_url }}"
        dest: "{{ workingdir.path }}/{{ platform_nodejs_url | basename }}"
        mode: "0755"

    - name: Install nodejs yum repo
      ansible.builtin.command: "{{ workingdir.path }}/{{ platform_nodejs_url | basename }}"
      changed_when: true

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: "{{ platform_nodejs_package }}"
        state: present

    - name: Remove workingdir
      ansible.builtin.file:
        path: "{{ workingdir.path }}"
        state: absent

- name: Install NodeJS (offline)
  ansible.builtin.include_role:
    name: offline
    tasks_from: install-rpms
  vars:
    offline_rpms_path: "{{ platform_offline_control_node_rpms_dir }}/nodejs"
  when: offline_install_enabled
