# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
yum_update: false

# Offline install settings
# Refer to the offline variables in common_vars for additional settings
packages_path: "{{ itential_packages_path }}/{{ iap_release }}/os"