# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# The location of the Redis log file
redis_log: /var/log/redis/redis.log

# The location of the Redis config file
redis_conf_path: /etc/redis
redis_conf_file: "{{ redis_conf_path }}/redis.conf"

# The name of the Redis data file
redis_db_filename: dump.rdb

# The location of the Redis data directory
redis_data_dir: /var/lib/redis

# Default redis port
redis_port: 6379

redis_owner: redis
redis_group: redis

# Flag to enable/disable IPv6
redis_bind_ipv6: true

# The bind address source
# Will default to inventory_hostname unless set to default_ipv4_address
redis_bind_addr_source: inventory_hostname

# The hostnames and/or IP addresses on which redis should listen for
# client connections, separated by spaces.
#
# If redis_bind_ipv6 is set to true, '::1' will be added to the
# redis_bind_addrs.
#
# The inventory_hostname or default_ipv4_address will be automatically added
# to the redis_bind_addrs depending on the redis_bind_addr_source.
redis_bind_addrs: 127.0.0.1

iap_redis_packages:
  - redis
  - jemalloc
