# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Validate pip_executable or python_venv is set
  ansible.builtin.fail:
    msg: "either pip_executable or python_venv must be set"
  when:
    - pip_executable is not defined
    - python_venv is not defined

- name: Validate wheels_dir is set
  ansible.builtin.fail:
    msg: "wheels_dir must be set"
  when: wheels_dir is not defined

- name: Install wheel files
  become_user: "{{ python_install_user }}"
  block:
    - name: Create temporary working directory
      ansible.builtin.tempfile:
        state: directory
      register: install_wheels_temp_dir

    - name: Copy wheel files to target node
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ install_wheels_temp_dir.path }}/{{ item | basename }}"
        mode: '0644'
      with_fileglob:
        - "{{ wheels_dir }}/*.whl"
        - "{{ wheels_dir }}/*.tar.gz"

    - name: Find wheel files on target node
      ansible.builtin.find:
        paths: "{{ install_wheels_temp_dir.path }}"
        patterns:
          - "*.whl"
          - "*.tar.gz"
      register: wheel_list

    - name: Install wheel files in virtual env
      ansible.builtin.pip:
        name: "{{ wheel_list.files | map(attribute='path') | list | sort }}"
        virtualenv: "{{ python_venv }}"
        extra_args: --no-index
      when: python_venv is defined

    - name: Install wheel files using pip executable
      ansible.builtin.pip:
        name: "{{ wheel_list.files | map(attribute='path') | list | sort }}"
        executable: "{{ pip_executable }}"
        extra_args: --no-index
      when: python_venv is not defined

    - name: Remove temporary working directory
      ansible.builtin.file:
        path: "{{ install_wheels_temp_dir.path }}"
        state: absent
