# Copyright (c) 2026, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

- name: Run Platform Certification Tasks
  hosts: platform*
  gather_facts: true
  become: true
  tasks:
    - name: Certify Platform Installation  # noqa run-once
      ansible.builtin.import_role:
        name: itential.deployer.platform
        tasks_from: certify-platform
      tags: certify-platform
