# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Install Redis
  hosts: redis, redis_secondary
  become: true
  roles:
    ### REDIS
    # Perform a base installation of Redis and optionally configure authorization and replication
    - role: itential.deployer.redis
      tags:
        - redis

- name: Install RabbitMQ
  hosts: rabbitmq, rabbitmq_secondary
  become: true
  roles:
    ### RABBITMQ
    # Perform a base installation of Rabbitmq
    - role: itential.deployer.rabbitmq
      tags:
        - rabbitmq
        - rabbitmq_install

    # Configure rabbit to only accept SSL connections
    - role: itential.deployer.rabbitmq_ssl
      when: rabbitmq_ssl | bool
      tags:
        - rabbitmq
        - rabbitmq_ssl

- name: Install MongoDB
  hosts: mongodb, mongodb_arbiter
  become: true
  roles:
    ### MONGODB
    # Perform a base installation of MongoDB
    # Many of the other component's settings with regard to IAP are stored in MongoDB.
    # Run these tasks on any defined arbiters as well.
    - role: itential.deployer.mongodb
      tags:
        - mongodb
        - mongodb_install

- name: Install Vault
  hosts: vault
  become: true
  roles:
    ## VAULT
    # Install and initialize Vault
    - role: itential.deployer.vault
      when: vault_install | bool
      tags:
        - vault
        - vault_install

    # Setup Vault (initialize server and unseal)
    - role: itential.deployer.vault_unseal
      when: vault_setup | bool
      tags:
        - vault
        - vault_setup

- name: Install IAP
  hosts: platform, platform_secondary
  become: true
  roles:
    ### IAP
    # Perform a base installation of IAP
    - role: itential.deployer.platform
      tags:
        - platform
        - platform_install

- name: Install IAP
  hosts: platform
  become: true
  roles:
    # Install app-artifact into IAP
    # This should only be done in a development environment
    - role: itential.deployer.platform_app_artifact
      when: app_artifact | bool
      tags:
        - platform
        - platform_app_artifact

- name: Install IAG
  hosts: gateway
  become: true
  roles:
    ### IAG
    # Perform a base installation of IAG
    - role: itential.deployer.gateway
      tags:
        - gateway
        - gateway_install

    - role: itential.deployer.gateway_haproxy
      when: iag_haproxy | bool
      tags:
        - gateway
        - gateway_haproxy
