# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
### MONGODB
- name: Install MongoDB
  hosts: mongodb, mongodb_arbiter
  become: true
  roles:
    # Pull in the common vars
    - role: itential.deployer.common_vars
      tags:
        - always

    # Perform a base installation of MongoDB.
    # Run these tasks on any defined arbiters as well.
    - role: itential.deployer.mongodb
