# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# Packages required to configure SELinux
redis_security_packages:
  - policycoreutils-python-utils

# Redis install from source - boolean
# When set to 'true' Redis will be installed from source.
# Otherwise Redis will be installed from YUM.
redis_install_from_source: true

# Packages required to build Redis from source
redis_build_packages:
  - tar
  - unzip
  - gcc
  - gcc-c++
  - make
  - systemd-devel

# The Remi and EPEL repos are used only when:
#  - redis_install_from_source is set to 'false'
#  - common_install_yum_repos is set to 'true'
#  - redis_packages contains 'remi'
redis_remi_repo_url: "http://rpms.remirepo.net/enterprise/remi-release-\
                     {{ ansible_distribution_version }}.rpm"
redis_epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-\
                     {{ ansible_distribution_major_version }}.noarch.rpm"
