# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# The location of the Redis binary
# redis_bin_dir: /usr/bin
redis_bin_dir: "{{ redis_install_from_source | bool | ternary('/usr/local/bin', '/usr/bin') }}"

# The location of the Redis config file
redis_conf_dir: "{{ redis_conf_dir_default }}"
redis_conf_file: "{{ redis_conf_dir }}/redis.conf"

# The location of the Redis log file
redis_log_dir: "{{ redis_log_dir_default }}"
redis_log: "{{ redis_log_dir }}/redis.log"

# The name of the Redis data file
redis_db_filename: dump.rdb

# The location of the Redis data directory
redis_data_dir: "{{ redis_data_dir_default }}"

# The location of the Redis data directory
redis_pid_dir: "{{ redis_pid_dir_default }}"

# Redis user and group
redis_owner: redis
redis_group: redis

# Default redis port
redis_port: "{{ redis_port_default }}"

# The default redis sentinel listen port
redis_sentinel_port: "{{ redis_sentinel_port_default }}"

# Flag to enable IPv6
redis_bind_ipv6: true

# The bind address source
# Will default to inventory_hostname unless set to default_ipv4_address
redis_bind_addr_source: inventory_hostname

# The hostnames and/or IP addresses on which redis should listen for
# client connections, separated by spaces.
#
# If redis_bind_ipv6 is set to true, '::1' will be added to the
# redis_bind_addrs.
#
# The inventory_hostname or default_ipv4_address will be automatically added
# to the redis_bind_addrs depending on the redis_bind_addr_source.
redis_bind_addrs: 127.0.0.1

# Feature flags that can be overridden in the hosts file
# Essentially, a default installation will have auth, but not replication or tls
redis_auth_enabled: true
redis_replication_enabled: false
redis_tls_enabled: false

# Default redis user passwords
# These are meant to be changed by the customer. By default they are meant to
# be predictable and simple.
redis_user_admin_password: admin
redis_user_itential_password: itential
redis_user_repluser_password: repluser
redis_user_sentineladmin_password: admin
redis_user_sentineluser_password: sentineluser
redis_user_prometheus_password: prometheus
